# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Research"
  url = "#research"
  weight = 2

[[main]]
  name = "People"
  url = "#people"
  weight = 3

[[main]]
  name = "Publications"
  identifier = "publications"
  weight = 4

[[main]]
  parent = "publications"
  name = "Selected publications"
  url = "#publications_featured"
  weight = 5

[[main]]
  parent = "publications"
  name = "Recent publications"
  url = "#publications"
  weight = 6

[[main]]
  name = "Teaching"
  url = "#teaching"
  weight = 7

[[main]]
  name = "Join the lab"
  url = "#join"
  weight = 8

[[main]]
  name = "Events"
  identifier = "events"
  weight = 9

[[main]]
  parent = "events"
  name = "SMEEB 2021"
  url = "https://liphlab.github.io/SMEEB2021/"
  weight = 10

[[main]]
  parent = "events"
  name = "Winter Workshop 2020"
  url = "/workshops/winter-workshop-2020"
  weight = 11

[[main]]
  parent = "events"
  name = "ConTaMiNEURO Summer School"
  url = "https://liphlab.github.io/ContamiNeuro/"
  weight = 12

[[main]]
  parent = "events"
  name = "Winter Workshop 2018"
  url = "/workshops/winter-workshop-2018"
  weight = 13

#[[main]]
#  name = "Collaborators"
#  identifier = "collaborators"
#  weight = 14

#[[main]]
#  parent = "collaborators"
#  name = "Collaboration network"
#  url = "#network"
#  weight = 15

#[[main]]
#  parent = "collaborators"
#  name = "Collaborators"
#  url = "#collaborators"
#  weight = 16

[[main]]
  name = "LIPh life"
  url = "/liphlife/gallery-calendar"
  weight = 17

[[main]]
    name = "Videos by the lab"
    url = "#videos"
    weight = 18

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 19



# Link to a PDF of your resume/CV from the
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
